// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using DevStack.OrmLite;
using DevStack.DataAnnotations;
using DevStack.Model;

namespace EfashionCool.Model
{
	[Serializable]
    public partial class a_articlesource 
    {
        [AutoIncrement]
		[PrimaryKey]
        public int Id { get; set;}
        public string Title { get; set;}
        public string KeyWords { get; set;}
        public string Description { get; set;}
        public string FromUrl { get; set;}
        public string FromDomain { get; set;}
        public string FromDomainName { get; set;}
        public string PublishUrl { get; set;}
        public string Author { get; set;}
        [Required]
        public DateTime CreateTime { get; set;}
    }
}
#pragma warning restore 1591
