




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `EfashionCool`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `server=123.56.222.226;uid=root;pwd=123456;initial catalog=efashioncoolarticle;`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `MySqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using DevStack.OrmLite;
using DevStack.DataAnnotations;
using DevStack.Model;

namespace EfashionCool.Model
{
}
#pragma warning restore 1591


